Admin_Login_App/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name='home'),

    # api urls

    # admin login
    path('admin_login_api', views.admin_login_api, name='admin_login_api'),
    path('user', views.admin_login_api),

    # course api
    path('course_api', views.courseApi, name='course_api'),
    path('update_course_api/<int:id>', views.courseApi, name='update_course_api'),
    path('delete_course_api/<int:id>', views.courseApi, name='delete_course_api'),

    # placement partners api
    path('partners_api', views.placementPartnersApi, name='partners_api'),
    path('update_partners_api/<int:id>', views.placementPartnersApi, name='update_partners_api'),
    path('delete_partners_api/<int:id>', views.placementPartnersApi, name='delete_partners_api'),

    # testimonial api
    path('testimonial_api', views.testimonialApi, name='testimonial_api'),
    path('update_testimonial_api/<int:id>', views.testimonialApi, name='update_testimonial_api'),
    path('delete_testimonial_api/<int:id>', views.testimonialApi, name='delete_testimonial_api'),

    # placement stories api
    path('placement_stories_api', views.placementStoriesApi, name='placement_stories_api'),
    path('update_placement_stories_api/<int:id>', views.placementStoriesApi, name='update_placement_stories_api'),
    path('delete_placement_stories_api/<int:id>', views.placementStoriesApi, name='delete_placement_stories_api'),

    # faq api
    path('faq_api', views.FaqApi, name='faq_api'),
    path('update_faq_api/<int:id>', views.FaqApi, name='update_faq_api'),
    path('delete_faq_api/<int:id>', views.FaqApi, name='delete_faq_api'),

    # blog api
    path('blog_api', views.BlogApi, name='blog_api'),
    path('update_blog_api/<int:id>', views.BlogApi, name='update_blog_api'),
    path('delete_blog_api/<int:id>', views.BlogApi, name='delete_blog_api'),

    # career api
    path('career_api', views.CareerApi, name='career_api'),
    path('update_career_api/<int:id>', views.CareerApi, name='update_career_api'),
    path('delete_career_api/<int:id>', views.CareerApi, name='delete_career_api'),



    path('course_list', views.course_list_view),

    path('course', views.course_page, name='course-page'),



    path('dashboard', views.dashboard_view, name='dashboard'),
    path('courses', views.courses_view, name='courses'),
    path('course_page', views.course_page_view, name='course_page'),
    path('update_course/<int:id>', views.update_course, name='update_course'),
    path('delete_course/<id>', views.delete_course),
    path('navbar_save_course', views.navbar_save_view, name='navbar_save_course'),
    path('partners_logo', views.partners_logo_view, name='partners_logo'),
    path('partners', views.partners_view, name='partners'),
    path('update_partners/<int:id>', views.update_partners, name='update_partners'),
    path('testimonial', views.testimonial_view, name='testimonial'),
    path('testimonial_form', views.testimonial_form_view, name='testimonial_form'),
    path('update_testimonial/<int:id>', views.update_testimonial, name='update_testimonial'),
    path('placement_stories', views.Placement_Stories_view, name='placement_stories'),
    path('update_stories/<int:id>', views.update_stories, name='update_stories'),
    path('stories_form', views.stories_form, name='stories_form'),
    path('faq', views.faq, name='faq'),
    path('faq_form_update/<int:id>/', views.faq_form_update, name='faq_form_update'),
    path('faq_add_form', views.faq_add_form, name='faq_add_form'),
    path('blog', views.blog_view, name='blog'),
    path('blog_add_form', views.blog_form, name='blog_add_form'),
    path('update_blog/<int:id>/', views.update_blog, name='update_blog'),
    path('careers', views.Careers_view, name='careers'),
    path('careers_form', views.Careers_form_view, name='careers_form'),
    path('update_careers/<int:id>/', views.update_blog, name='update_careers'),
    path('user_home', views.user_home, name='user_home'),
    path('login', views.login_view, name='login'),
    path('admin_login', views.admin_login_view, name='admin_login'),
    path('register', views.register_view, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('report', views.report_view, name='report'),
]

Admin_Login_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Admin_Login_App.urls')),
]

Admin_Login_App/models.py
import datetime
import os
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from ckeditor.fields import RichTextFormField

# Create your models here.

def getFileName(request,filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time,filename)
    return os.path.join('Images/',new_filename)
 
def getlogo(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time,filename)
    return os.path.join('logo/',new_filename)

def picture(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time,filename)
    return os.path.join('picture/',new_filename)

def video(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time,filename)
    return os.path.join('video/',new_filename)

def blog_images(request, filename):
    now_time = datetime.datetime.now().strftime('%Y%m%d%X')
    new_filename = "{}{}".format(now_time,filename)
    return os.path.join('media/',new_filename)

class AdminLoginManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        # User creation logic
        if not email:
            raise ValueError('User must have an email.')
        if not username:
            raise ValueError('User must have a username.')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        # Superuser creation logic
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class AdminLogin(AbstractBaseUser):
    username = models.CharField(max_length=100, unique=True, blank=False)
    email = models.CharField(max_length=150, unique=True, blank=False)
    password = models.CharField()
    ph_no = PhoneNumberField(region='US', unique=True, blank=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = AdminLoginManager()


class courses(models.Model):
    Title = models.CharField(max_length=100, null=False, blank=False)
    Description = models.TextField()
    Technologies = models.CharField(max_length=150)
    Images = models.ImageField(upload_to= getFileName, blank=False)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.Title

class technologies(models.Model):
    Technologies = models.CharField(max_length=150)


# placement partners

class partners_logo(models.Model):
    name = models.CharField(max_length=100, default=None)
    logo = models.ImageField(upload_to=getlogo)
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)
    created_by=models.IntegerField(null=True,blank=True)
    modified_by=models.IntegerField(null=True)
    is_active=models.BooleanField(default=True)
    is_deleted=models.BooleanField(default=False)

# testimonial 

class Testimonial(models.Model):
    student_name = models.CharField(max_length=100)
    picture = models.ImageField(upload_to=picture, blank=False)
    course = models.CharField(max_length=100)
    date = models.DateField()
    testimonial = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True,blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

# Placement Stories

class PlacementStories(models.Model):
    student_name = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    testimonial_video = models.FileField(upload_to=video, blank=False)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True,blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)


# FAQ

class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True,blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

# Blog

class Blog(models.Model):
    images = models.ImageField(upload_to=blog_images, blank=False)
    title = models.CharField(max_length=100)
    description = models.TextField()
    course = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True,blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

# Careers

class Careers(models.Model):
    Logo = models.ImageField(upload_to=getlogo, blank=False)
    Job_Heading = models.CharField(max_length=100)
    Location = models.CharField(max_length=100)
    Experience = models.CharField(max_length=100)
    No_Of_Openings = models.CharField(max_length=100)
    Salary = models.FloatField()
    Status = models.BooleanField(default=True)

    Job_Type = models.CharField(max_length=100)
    Qualification = models.CharField(max_length=255)
    Job_Description = models.TextField()
    Skills_Required = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.IntegerField(null=True,blank=True)
    modified_by = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

Admin_Login_App/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from ckeditor.widgets import CKEditorWidget  # Import CKEditorWidget
from .models import *

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = AdminLogin
        fields = ('username', 'email', 'ph_no', 'password')

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()

        return user

class PartnersLogoForm(forms.ModelForm):
    class Meta:
        model = partners_logo
        fields = ['name', 'logo']

class UpdataCourseForm(forms.Form):
    Title = forms.CharField(max_length=100)
    Description = forms.CharField(widget=forms.Textarea)
    Technologies = forms.CharField(max_length=150)
    Images = forms.ImageField()
    status = forms.BooleanField()

class FaqForm(forms.ModelForm):  # Change to ModelForm
    class Meta:
        model = FAQ
        fields = ['question', 'answer']
        widgets = {
            'answer': CKEditorWidget()  # Use CKEditorWidget for 'answer' field
        }

templates/Admin_Login_App/Admin_Header.html
{% extends 'Admin_Login_App/base.html' %}
{% load static %}
{% load bootstrap_icons %}

{% block content %}

<div class="container-fluid" id="header">
    <div class="row">
        <div class="col-2 icon-div border">
            <a class="navbar-brand" href="#">
                <!-- <button class="navbar-toggler tog" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    {% bs_icon 'list' %}
                </button> -->
                <img src="{% static '/images/logo.png' %}" class="hideimg">
            </a>
        </div>
        <div class="col-10 ">
            <div class="collapse navbar-collapse d-flex justify-content-end navbar-div navi" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <div class="row">
                        <div class="col demo-div">
                            <li class="nav-item dropdown border">
                                <a class="nav-link dropdown-toggle " href="#" id="user" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img id="profile-img" src="{% static '/images/profile.png' %}" alt="profile">
                                    Demo User
                                </a>
                                <ul class="dropdown-menu dropdown-menu-ul">
                                    <li><a class="dropdown-item ps-4 pe-4 pt-2 pb-2" href="#">{% bs_icon 'person-circle' %} Your Profile</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="dropdown-store">Stores</li>
                                    <li><a class="dropdown-item ps-4 pe-4 pt-2 pb-2" href="#">My Demo shop</a></li>
                                </ul>
                            </li>
                        </div>
                        <div class="col logout-div">
                            <li class="nav-item float-start">
                                <a class="nav-link active logout" aria-current="page" href="/logout">
                                    <?xml version="1.0" ?><svg height="14" viewBox="0 0 1792 1792" width="14" xmlns="http://www.w3.org/2000/svg"><path d="M704 1440q0 4 1 20t.5 26.5-3 23.5-10 19.5-20.5 6.5h-320q-119 0-203.5-84.5t-84.5-203.5v-704q0-119 84.5-203.5t203.5-84.5h320q13 0 22.5 9.5t9.5 22.5q0 4 1 20t.5 26.5-3 23.5-10 19.5-20.5 6.5h-320q-66 0-113 47t-47 113v704q0 66 47 113t113 47h312l11.5 1 11.5 3 8 5.5 7 9 2 13.5zm928-544q0 26-19 45l-544 544q-19 19-45 19t-45-19-19-45v-288h-448q-26 0-45-19t-19-45v-384q0-26 19-45t45-19h448v-288q0-26 19-45t45-19 45 19l544 544q19 19 19 45z"/></svg> 
                                    <span class="log">Logout</span>
                                </a>
                            </li>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/Admin_Login_App/User_Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login Dashboard</h1>
    <a href="/user_logout"><label for="name">{{user.username}}</label><input id="name" type="submit" value="Logout"></a>
</body>
</html>

templates/Admin_Login_App/blog.html
{% extends 'Admin_Login_App/base.html' %}
{% load static %}
{% load bootstrap_icons %}

<!-- title -->
{% block title %} Blog {% endblock %}

<!-- Link css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/Admin_Header.css' %}">
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'css/side_navbar.css' %}">
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'css/course_page.css' %}">
<link rel="stylesheet" href="{% static 'css/course_list.css' %}">
{% endblock %}

<!-- link js -->
{% block link_js %}

{% endblock %}

<!-- header -->
{% block header %}
{% include 'Admin_Login_App/Admin_Header.html' %}
{% endblock %}

<!-- body content -->
{% block content %}

<div class="container-fluid">
    <div class="row bg-body-tertiary">

        <!-- side navbar -->

        {% block sidenavbar %}

        {% include 'Admin_Login_App/Side_Navbar.html' %}

        {% endblock %}

        <!-- navbar -->
        <div class="col-10 pb-5" style="background-color: #f6f6f6;">
            <div class="row">

                {% block blog_navbar %}

                <div id="navbar-content">

                    {% include 'Admin_Login_App/blog_navbar.html' %}

                </div>

                {% endblock %}


                {% block blog_list %}

                <div id="blog-content">
                    <!-- This is where the course content will be displayed -->

                    {% include 'Admin_Login_App/blog_list.html' %}

                </div>
                {% endblock %}


            </div>
        </div>

    </div>
</div>

{% endblock %}

{% block scripts %}
<script>
    // v1
    // Function to check all checkboxes
    function checkAll() {
        var checkboxes = document.querySelectorAll('.check');
        var checkallCheckbox = document.getElementById('checkall');

        checkboxes.forEach(function (checkbox) {
            checkbox.checked = checkallCheckbox.checked;
        });
    }

    function loadBlogPage() {
        
        // Specify the URL from which to fetch the new content
        const url = "{% url 'blog_add_form' %}";

        // Fetch content from the URL using the provided URL
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.text();
            })
            .then(html => {
                // Replace the HTML content of a specific div with the fetched data
                document.getElementById('blog-content').innerHTML = html;
            })
            .catch(error => console.error('Fetch error:', error));
    }
    
    function updateBlogPage(url) {

        // Fetch content from the URL using the provided URL
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.text();
            })
            .then(html => {
                // Replace the HTML content of a specific div with the fetched data
                document.getElementById('blog-content').innerHTML = html;
            })
            .catch(error => console.error('Fetch error:', error));
    }
</script>
{% endblock %}

templates/Admin_Login_App/blog_add_form.html
{% load static %}
{% load bootstrap_icons %}

{% block blog_list %}
<div class="container" id="specific-div">
 
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="panel panel-default border">
                    <div class="panel-heading ps-3">
                        <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'pencil' %}  <span class="Add_Course">Add Blog</span></h3>
                    </div>
                    <div class="panel-body bg-white px-3 py-3">
                        <form method="post"  enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <div>
                                    <input type="text" name="title" id="title" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="id_description">Description</label>
                                <textarea id="id_description" name="description" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="title">Courses</label>
                                <div>
                                    <input type="text" name="course" id="title" class="form-control" autocomplete="off">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="images">Images</label>
                                <input type="file" name="images" id="images" class="form-control-file">
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   
</div>
{% endblock %}

templates/Admin_Login_App/blog_navbar.html
{% load static %}
{% load bootstrap_icons %}

{% block blog_navbar %}

    <div class="col-12" id="navbar-content">
        <div class="row py-3">
            <div class="col-10">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                        <a class="navbar-brand Dashboard" href="#">
                            <h1>Blog</h1>
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse " id="navbarSupportedContent">
                            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                                <ol class="breadcrumb navbar-div">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active text-info" aria-current="page"><a href="#">Blog</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="col-2 d-flex justify-content-end">
                <a ><button onclick="loadBlogPage()" data-toggle="tooltip" title="Add New" type="button" class="btn" id="plus"><span class="plus">+</span></button></a>
                <a href="#"><button data-toggle="tooltip" title="Delete" type="button" class="btn" id="trash">{% bs_icon 'trash'%}</button></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/Admin_Login_App/faq_add_form.html
{% load static %}
{% load bootstrap_icons %}

{% block faq_list %}
<div class="container" id="specific-div">
 
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="panel panel-default border">
                    <div class="panel-heading ps-3">
                        <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'pencil' %}  <span class="Add_Course">Add FAQ</span></h3>
                    </div>
                    <div class="panel-body bg-white px-3 py-3">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p|safe }}
                            <!-- <div class="form-group">
                                <label for="title">Question</label>
                                <div>
                                    <input type="text" name="question" id="title" class="form-control" autocomplete="off">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="id_description">Answer</label>
                                <textarea id="id_description" name="answer" class="form-control"></textarea>
                            </div>
                             -->
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                        <!-- <script>
                            CKEDITOR.replace('{{ form.answer.id_for_label }}');
                        </script> -->
                    </div>
                </div>
            </div>
        </div>
   
</div>

{% endblock %}

templates/Admin_Login_App/faq_update_form.html
{% load static %}
{% load bootstrap_icons %}

{% block partners_list %}
<div class="container" id="specific-div">

    <div class="row">
        <div class="col-12 mx-auto">
            <div class="panel panel-default border">
                <div class="panel-heading ps-3">
                    <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'pencil' %} <span class="Add_Course">Edit
                            Courses</span></h3>
                </div>
                <div class="panel-body bg-white px-3 py-3">
                    <form method="POST" action="{% url 'faq_form_update' data.id %}" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="title">Question</label>
                            <div>
                                <input type="text" name="question" id="title" value="{{ data.question }}" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="title">Answer</label>
                            <div>
                                <input type="text" name="answer" value="{{ data.answer }}" class="form-control">
                            </div>
                        </div>
                    
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/Admin_Login_App/partners_navbar.html
{% load static %}
{% load bootstrap_icons %}

{% block partners_navbar %}
    <div class="col-12" id="navbar-content">
        <div class="row py-3">
            <div class="col-10">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                        <a class="navbar-brand Dashboard" href="#">
                            <h1>Partners</h1>
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse " id="navbarSupportedContent">
                            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                                <ol class="breadcrumb navbar-div">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active text-info" aria-current="page"><a href="#">Partners</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="col-2 d-flex justify-content-end">
                <a ><button onclick="loadPartnersPage()" data-toggle="tooltip" title="Add New" type="button" class="btn" id="plus"><span class="plus">+</span></button></a>
                <a href="#"><button data-toggle="tooltip" title="Delete" type="button" class="btn" id="trash">{% bs_icon 'trash'%}</button></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/Admin_Login_App/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register Form</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</body>
</html>

templates/Admin_Login_App/update_blog.html
{% load static %}
{% load bootstrap_icons %}

{% block blog_list %}
<div class="container" id="specific-div">
 
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="panel panel-default border">
                    <div class="panel-heading ps-3">
                        <h3 class="panel-title border-bottom pb-2"> {% bs_icon 'pencil' %}  <span class="Add_Course">Edit Blog</span></h3>
                    </div>
                    <div class="panel-body bg-white px-3 py-3">
                        <form method="post" action="{% url 'update_blog' datas.id %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <div>
                                    <input type="text" name="title" id="title" value="{{ datas.title }}" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="id_description">Description</label>
                                <textarea id="id_description" name="description" class="form-control"> {{ datas.description }} </textarea>
                            </div>
                            <div class="form-group">
                                <label for="title">Courses</label>
                                <div>
                                    <input type="text" name="course" id="title" value="{{ datas.course }}" class="form-control" autocomplete="off">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="images">Images</label>
                                <img src="{{ datas.images.url }}" alt="{{ datas.images }}" style="max-height: 40px;">
                                <input type="file" name="images" id="images" class="form-control-file">
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   
</div>
{% endblock %}